services:
  eureka-server:
    build: ../Eureka
    ports:
      - "8761:8761"

  user-service:
    build: ./user-service
    ports:
      - "5001:5001"
    volumes:
      - user_data:/app
    environment:
      - FLASK_ENV=development
      - EUREKA_URL=http://eureka-server:8761/eureka

  product-service:
    build: ./product-service
    ports:
      - "5002:5002"
    volumes:
      - product_data:/app
    environment:
      - FLASK_ENV=development
      - EUREKA_URL=http://eureka-server:8761/eureka

  notification-service:
    build: ./notification-service
    ports:
      - "5004:5004"
    environment:
      - FLASK_ENV=development
      - EUREKA_URL=http://eureka-server:8761/eureka

  order-service:
    build:
      context: ./order-service
    ports:
      - "5003:5003"
    volumes:
      - order_data:/app
    depends_on:
      - user-service
      - product-service
      - notification-service
    environment:
      - FLASK_ENV=development
      - EUREKA_URL=http://eureka-server:8761/eureka

volumes:
  user_data: {}
  product_data: {}
  order_data: {}
