
services:
  user-service:
    build: ./user-service
    ports:
      - "5001:5001"
    volumes:
      - user_data:/app
    environment:
      - FLASK_ENV=development
    networks:
      - ms-network

  product-service:
    build: ./product-service
    ports:
      - "5002:5002"
    volumes:
      - product_data:/app
    environment:
      - FLASK_ENV=development
    networks:
      - ms-network

  product-service-2:
    build: ./product-service
    ports:
      - "5006:5002"  # dış port farklı
    volumes:
      - product_data:/app
    environment:
      - FLASK_ENV=development
    networks:
      - ms-network


  order-service:
    build:
      context: ./order-service
    ports:
      - "5003:5003"
    volumes:
      - order_data:/app
    depends_on:
      - user-service
      - product-service
      - notification-service
    environment:
      - FLASK_ENV=development
      - USER_SERVICE_URL=http://user-service:5001
      - PRODUCT_SERVICE_URL=http://product-service:5002
      - NOTIFICATION_SERVICE_URL=http://notification-service:5004
    networks:
      - ms-network

  notification-service:
    build: ./notification-service
    ports:
      - "5004:5004"
    environment:
      - FLASK_ENV=development
    networks:
      - ms-network

volumes:
  user_data: {} 
  product_data: {} 
  order_data: {} 

networks:
  ms-network:
    driver: bridge